CD=cd
NPM=npm

all:
	@echo "BioASQ Annotation Tool"
	@echo ""
	@echo "available targets:"
	@echo "  libs -- install dependencies via npm"

libs:
	$(CD) lib && $(NPM) install journey
	$(CD) lib && $(NPM) install optimist
