CD=cd
NPM=npm install
LIB=.
DEPS=journey optimist mongodb sesh response eyes schemajs nodemailer

all:
	@echo ""
	@echo "BioASQ Annotation Tool"
	@echo ""
	@echo "available targets:"
	@echo "  libs -- locally installs node dependencies via npm"

libs:
	$(CD) $(LIB) && $(NPM) $(DEPS)
